### ISSUE TITLE
Javascript and Stylesheet loading order

### ISSUE THREAD

**Issue by Scrabble96** [sniggle/joomla-bootstrap4-template#10]
I believe a few items in the index.php need reordering for optimization (javascript) and heirarchy (css):

**Javascript:**
Bootstrap 4.0 says ([here](https://getbootstrap.com/docs/4.0/getting-started/introduction/))

> Many of our components require the use of JavaScript to function. Specifically, they require jQuery, Popper.js, and our own JavaScript plugins. Place the following <script>s near the end of your pages, right before the closing </body> tag, to enable them. jQuery must come first, then Popper.js, and then our JavaScript plugins.

However, your template loads JavaScript in the head of the template, before the CSS. 

**CSS:** 
template.css should be loaded _after_ bootstrap.min.css to ensure that any new css takes priority.

**Comment by Dade88** [comment]
Please test #11 :)

**Comment by jwiesel** [comment]
fixed in release 1.8
