### ISSUE TITLE
Wrong order of .css files

### ISSUE THREAD

**Issue by Mangaclub** [sniggle/joomla-bootstrap4-template#12]
// Add Stylesheets
$doc->addStyleSheet($this->baseurl . '/templates/' . $this->template . '/css/template.css');
$doc->addStyleSheet($this->baseurl . '/templates/' . $this->template . '/css/bootstrap.min.css');
$doc->addStyleSheet($this->baseurl . '/templates/' . $this->template . '/css/font-awesome.min.css');

is a wrong order of requestion css files. template css always will get overwritten bei bootstrap.min.css

// Add Stylesheets
$doc->addStyleSheet($this->baseurl . '/templates/' . $this->template . '/css/bootstrap.min.css');
$doc->addStyleSheet($this->baseurl . '/templates/' . $this->template . '/css/font-awesome.min.css');
$doc->addStyleSheet($this->baseurl . '/templates/' . $this->template . '/css/template.css');

is a correct load order for styling this template via template.css

**Comment by jwiesel** [comment]
Hi @Mangaclub ,
the issue has been fixed recently.
It will be part of the next release.

**Comment by jwiesel** [comment]
fixed in release 1.8
