### ISSUE TITLE
Blog layouts

### ISSUE THREAD

**Issue by Scrabble96** [sniggle/joomla-bootstrap4-template#14]
I am unable to display a blog in anything other than a single column, even on a wide desktop. This seems to be a conflict between Bootstrap 4.0 using col-md-12, col-md-6 etc and the current Joomla blog layouts which use rows and spans, where span6 is the near equivalent of col-md-6, for example. I've no idea how to get around this before Joomla 4.0 is released.

**Comment by Scrabble96** [comment]
I think I have answered my own query by adding this code to the end of my index.php just before the closing body tag:

`<script>
$( ".blog > .items-row" ).addClass( "row" );
$( ".blog > .items-row > .span6" ).addClass( "col-md-6" );
$( ".blog > .items-row > .span4" ).addClass( "col-md-4" );
$( ".blog > .items-row > .span3" ).addClass( "col-md-3" );
</script>
`
I'm sure this code would be better in a js file but I don't know how to do this yet (I'm a js beginner)

**Comment by jwiesel** [comment]
Hi @Scrabble96 ,
thanks for mentioning! There are multiple ways adding the classes.
It can be done generically via jQuery like you did or using layout overrides. I just create an override for components/com_content/views/category/blog.php which achieves the same result. Feel free to download the current source to give it a try. I just committed the override: https://github.com/sniggle/joomla-bootstrap4-template/archive/master.zip It will be part of the next version automatically. ;)

**Comment by Scrabble96** [comment]
Many thanks. I will have a look.

**Comment by jwiesel** [comment]
Hi @Scrabble96 ,
not sure if something is still open here. Hence I'll close the ticket. Feel free to reopen it, if needed.
