### ISSUE TITLE
Menu off canvas

### ISSUE THREAD

**Issue by roman5527** [sniggle/joomla-bootstrap4-template#17]
Hi, I think it would be good to integrate off the canvas menu. What do you think ?
Setting the template might be the choice.

**Comment by jwiesel** [comment]
Hi @roman5527 ,
what do you mean by "off the canvas menu"? are you speaking of a special bootstrap component or do you mean adding a nav to a special place in the grid? Do you have an example?

**Comment by jwiesel** [comment]
@roman5527 since there was no response, I'll close the issue for now.
Please feel free to reopen and add further details. :-)
