### ISSUE TITLE
language

### ISSUE THREAD

**Issue by dmachado48** [sniggle/joomla-bootstrap4-template#18]
the customisation of the module language, point to fbxfacing folder but it doesnt exist. Where can i found this icons? Many thanks

**Comment by vol-mir** [comment]
Hey. Russian version ru-RU

[ru-RU.zip](https://github.com/sniggle/joomla-bootstrap4-template/files/1974330/ru-RU.zip)

**Comment by jwiesel** [comment]
Hi @dmachado48 ,
thanks for pointing that out. Apparently I missed that, when initially creating the template. In one of the projects I replaced the language icons with svgs.
I just deleted the override. Please delete the following folder in your project. Then your issue should be resolved: "templates/bootstrap4/html/mod_languages"

**Comment by jwiesel** [comment]
Hi @vol-mir ,
thanks for providing the Russian translation. I just added it. Will be part of verson 1.10.
