### ISSUE TITLE
Google analytics code

### ISSUE THREAD

**Issue by roman5527** [sniggle/joomla-bootstrap4-template#19]
Hi I integrated filed for Google Analytics code in template. 

I add strings to anguage files but I translate it only with Google Translator. 

[bootstrap4.zip](https://github.com/sniggle/joomla-bootstrap4-template/files/1994626/bootstrap4.zip)

**Comment by jwiesel** [comment]
Hi @roman5527 ,
thanks for sharing!
There are various Joomla plugins out there to add Tracking scripts. Below are just some examples:
* Google Analytics: https://extensions.joomla.org/extensions/extension/site-management/analytics/asynchronous-google-analytics/
* Piwik: https://extensions.joomla.org/extensions/extension/site-management/analytics/nfrpiwik/

I personally stopped using GA on my sites to protect the privacy of my page visitors.
For these reasons I would like to give every user of the template the choice to decide themselves, if they want to use tracking and if so, if the data should go to google or somewhere else.

Feel free to fork the project to provide a "GA" flavour of the Bootstrap 4 template.
