### ISSUE TITLE
Next & Prev navigation has no style

### ISSUE THREAD

**Issue by andrewpthompson** [sniggle/joomla-bootstrap4-template#22]
Hi. I'm seeing a problem with the Next & Prev links that are generated by the "Content - Page Navigation" plugin at the bottom of articles. They display as a plain bulleted list and don't get any Bootstrap styling as buttons.

To be clear these are the navigation links that are displayed at the bottom of articles when the "Content - Page Navigation" is enabled, and in the global Articles component configuration "Show Navigation" is set to "Show".

![image](https://user-images.githubusercontent.com/25069773/42790539-c61dadb4-89aa-11e8-8f9e-dc81ebc21754.png)

**Comment by jwiesel** [comment]
Hi @andrewpthompson ,
thanks for the detailed explanation. Apparently the Content-Plugin "Page Navigation" was not supported by the plugin so far.
But in the new version it will be. I just added the code. :-)

**Comment by jwiesel** [comment]
Version v1.11 is out now ;-)

**Comment by andrewpthompson** [comment]
Thanks very much @jwiesel. I just tested this and it works really well.
