### ISSUE TITLE
Featured articles not displaying in columns

### ISSUE THREAD

**Issue by Scrabble96** [sniggle/joomla-bootstrap4-template#24]
I see that for version 1.10 blog articles layout now displays correctly in columns. However, if you set a menu to type Articles > Featured Articles they still only display in one column. An update for version 1.11, please? Thank you.

**Comment by jwiesel** [comment]
Hi @Scrabble96 ,
understood your point. Apparently joomla uses different views for Blog and Featured Articles layouts.
I just added support for featured articles. Will be part of the next version.

**Comment by jwiesel** [comment]
Version v1.11 is out now ;-)
