### ISSUE TITLE
Bootstrap 4.1.3

### ISSUE THREAD

**Issue by renekreijveld** [sniggle/joomla-bootstrap4-template#25]
Can you update the template to Bootstrap 4.1.3?

**Comment by Dade88** [comment]
Please unzip this files into bootstrap4 template root and test if it's working.
[updated_assets.zip](https://github.com/sniggle/joomla-bootstrap4-template/files/2498355/updated_assets.zip)
 I had no issues so far :)

**Comment by Dade88** [comment]
#28 Sent

**Comment by jwiesel** [comment]
Hi @renekreijveld ,
I just added some  enhancements to create a new version 1.11.
Bootstrap will be updated to the latest version as part of that.

**Comment by renekreijveld** [comment]
Cool, thanks!

**Comment by jwiesel** [comment]
Version v1.11 is out now ;-)
