### ISSUE TITLE
Language file

### ISSUE THREAD

**Issue by roman5527** [sniggle/joomla-bootstrap4-template#3]
Hi, i see problem with template language string . zou can see img. 
![error_template](https://user-images.githubusercontent.com/4589295/29475804-9f2c57e0-8461-11e7-8ce6-0d76dbf0a366.jpg)

**Comment by jwiesel** [comment]
Hi @roman5527, thanks for sharing! Which version of the template do you use as a starting point? In the current version, there should not a a "logo" field anymore. Feel free to remove the field from templateDetails.xml in your template.

**Comment by roman5527** [comment]
Hi, I upgrade to version 1.4 . 

Logo field is my custom work. 
but neither field favicon does not catch the string.

`http://prntscr.com/glz0la`

`http://prntscr.com/glz0xr`

`http://prntscr.com/glz179`

**Comment by jwiesel** [comment]
Hi, okay got it.
I could reproduce the same issue in the core-template. Reason: The Favicon string was only present in the .sys.ini, but not in the normal .ini-file. After adding it you should see the label under "Advanced" template settings. See also Release 1.5.
P.S: I would be happy to add support for additional languages. Let me know, if you would like to contribute language files ;)

**Comment by roman5527** [comment]
Good day . Yes, I can deal with the Slovak language.

**Comment by roman5527** [comment]
Where I can send SK ini files ?

**Comment by jwiesel** [comment]
Hi,
you can do it in different ways. Either
* drag & drop the files into the comment field here
* Add the contents of the files as code block to a comment
* Fork the language folder, push the files and post a link in a comment
I guess there are other ways with Pull & Merge, etc. but for a one-time activity maybe the above is easier.
Thanks for your support!

**Comment by jwiesel** [comment]
Hi @roman5527 ,
thanks for providing the sk-SK language files.
I just added them. They will be part of the new release

**Comment by jwiesel** [comment]
fixed in release 1.8
