### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by N6REJ** [sniggle/joomla-bootstrap4-template#32]
I get a 404 error after installing the template.
![image](https://user-images.githubusercontent.com/1850089/71132820-3383cd00-21be-11ea-96b5-a2250db7bc26.png)

**Comment by N6REJ** [comment]
is this project dead?

**Comment by jwiesel** [comment]
Hi @N6REJ ,
thanks for reaching out. Can you provide some more details?
* Does the error "500 - JHhtmlBehavior: caption not found" error also occur in the default frontend template? (protostar)
* Which joomla version do you use?
* What kind of menu entry is your default page? (butternut.local)
* Does the page work with a different default page (e.g. Articles > Single Article)

**Comment by N6REJ** [comment]
@jwiesel I"m going to close this issue because after numerous installs I got it to display properly.  I've since taken the template a VERY long ways and am only struggling with the menu system now.
I REALLY appreciate you stepping back in to fix that issue. I'll be testing it in a hour or so
