### ISSUE TITLE
Dropdown links not visible (white) for navbar-dark bg-dark navbars

### ISSUE THREAD

**Issue by mischmidt83** [sniggle/joomla-bootstrap4-template#4]
Hi,

thanks for the nice project!

For navbar-dark bg-dark navbar the dropdown links are white (not visible). The code to fix it, was there already, but commented.

Uncommenting the code fixed the issue
https://github.com/mischmidt83/1sr_bs4/commit/c8afda18d95681b597f8bc9d1f597caff1f89fb0

Kind regards,

Michael

**Comment by jwiesel** [comment]
Hi,
thanks for the remark, hint and snippet!
I guess the snippet caused problems in an earlier version of Bootstrap 4. I just tested it. Now the code is active again and everything works. P.S: I added some other nice enhancements for better mobile device support. :)
Jochen
