### ISSUE TITLE
Not close tag h1 and double ;;

### ISSUE THREAD

**Issue by makeweb-by** [sniggle/joomla-bootstrap4-template#41]
https://github.com/sniggle/joomla-bootstrap4-template/blob/c145dda90e65b1de3900fe285a60d76010436114/bootstrap4/index.php#L94

**Comment by jwiesel** [comment]
Thanks for mentioning and sorry for the late response @makeweb-by !
The issue has just been fixed and will be part of the next release and is now available via "Download > Zip"
