### ISSUE TITLE
Navbar dissappears

### ISSUE THREAD

**Issue by josflachs** [sniggle/joomla-bootstrap4-template#5]
Hi,

I've got a weird problem: my navbar disappears: 
- I added a scss folder, with the Bootstrap 4 sass files (alpha 6).
- Create my own bootstrap with it. Compile it to style.css. 
- Deactivate bootstrap.css, add style.css instead. 

Result: everything works, but the navbar is no longer there.

**Comment by N6REJ** [comment]
Sounds like a bootstrap issue not template issue.

**Comment by jwiesel** [comment]
agree to @N6REJ .
If there are problems with the template itself, feel free to reopen the issue and add further details.
