### ISSUE TITLE
Template ignores Link CSS Style

### ISSUE THREAD

**Issue by boldc** [sniggle/joomla-bootstrap4-template#7]
Hello, thanks for creating this template!

I have tried adding css to menu links using the **Link CSS Style** parameter (_Admin > Menus > Main Menu > Home > Link Type > Link Css Style_) but it appears that **/templates/bootstrap4/html/mod_menu/default.php** ignores this parameter and simply adds "nav-link" to every menu item:

line 73: **$item->anchor_css = 'nav-link';**

So every menu item's output is **<a class="nav-link"**...

Is this something you would be willing to address?

Thanks for your time!

EDIT:  There is no css markup for "nav-link" in template.css. I would recommend removing line 73 - this appears to resolve the issue.

**Comment by jwiesel** [comment]
Hi @boldc,
thanks for sharing! This line has been added to support Bootstrap 4 Navs (https://getbootstrap.com/docs/4.0/components/navs/). I just changed the code to support both. the nav-link class + the link-class specified in the Joomla! backend. 
$item->anchor_css = 'nav-link' . $item->anchor_css;
By that you can either add your own class by adding " myclass", or you can deactivate the nav-link class by adding e.g. "del myclass"
Just upgrade to the latest version :)

**Comment by boldc** [comment]
Great - thanks!  And thanks again for taking Joomla into the world of Bootstrap 4 :-)
