### ISSUE TITLE
Container and container-fluid

### ISSUE THREAD

**Issue by Scrabble96** [sniggle/joomla-bootstrap4-template#8]
I am in the process of creating my own Joomla 3.8.5 Bootstrap 4.0 template completely from scratch (whilst teaching myself PHP, js, Bootstrap 4.0 etc as I go along).  This is my first post on GitHub, so please excuse me if I'm not following the correct format.

I have also installed your template on another site in order to compare notes.

In your index.php from line 95 you have the following code:

`                <div class="container<?php echo ($params->get('fluidContainer') ? '-fluid' : ''); ?>">
                    <jdoc:include type="modules" name="banner" style="xhtml" />
                    <?php if ($this->countModules('breadcrumbs')) : ?>
                        <div class="row">
                            <div class="col-sm-12">
                                <jdoc:include type="modules" name="breadcrumbs" style="xhtml" />
                            </div>
                        </div>`

But what I can't understand is why you just don't have this:

`                <div class="container">
                    <jdoc:include type="modules" name="banner" style="xhtml" />
                    <?php if ($this->countModules('breadcrumbs')) : ?>
                        <div class="row">
                            <div class="col">
                                <jdoc:include type="modules" name="breadcrumbs" style="xhtml" />
                            </div>
                        </div>`

i.e. the container class in the first line and the column class later on. If you look at the html output for your template, you end up with class="container" anyway, and "col-sm-12" and "col" have the same result.

**Comment by jwiesel** [comment]
Hi @Scrabble96 , thanks for sharing!
Actually I removed the fluid-container support when initially creating the template.
I just added the parameter to the advanced template parameters again.
You can use it in the next version of the template.

**Comment by jwiesel** [comment]
fixed in release 1.8
